GET http://localhost:8010/products



### Create product
POST http://localhost:8010/product
Content-Type: application/json

{
    "id": 1,
    "name": "Apple iPhone XR",
    "price": 41999.00,
    "created_on": "2021-05-21T18:24:00Z"
}